apiVersion: apps/v1
kind: Deployment
metadata:
  name: hr-deployment
spec: # It define the behavior of ReplicaSet
  replicas: 2 # It defines the number of Pod replicas
  selector: # It is used to find the Pods that this ReplicaSet will manage
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec: # Defines the behavior of Pod
      containers:
        - name: web-hr
          image: avi364/cap-hrmanage:v1.1.1
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata: 
  name: hr-service
spec: 
  selector: 
    app: web
  ports: 
   - port: 3001
     targetPort: 3000
     protocol: TCP
  type: LoadBalancer


